### PR TITLE
docs: use new `nuxi module add` command in installation

### PR DESCRIPTION
**Pull request by danielroe**
This updates the documentation to use the [`nuxi module add` command](https://github.com/nuxt/cli/pull/197) which should simplify docs a bit and also improve user experience as there's no need to add to `nuxt.config` manually.

It's documented [here](https://nuxt.com/docs/api/commands/module#nuxi-module-add).

I may have missed a few spots in the documentation as I'm doing this across the modules ecosystem assisted by the power of regular expressions ✨, so I'd appreciate a review 🙏

### CODE REVIEW

**Comment by Chris2011** [comment]
Hey @danielroe that's definitely a neat little feature to mention it. Thx for your PR :)

**Review by Chris2011 — APPROVED** [review]

**Comment by Chris2011** [comment]
As I understand it correct, part two of the readme is not necessary after nuxi module add. Should we remove it also from the readme or still have it as a "backup". What do you think?

**Comment by danielroe** [comment]
I am happy either way. I didn’t remove it as I think it doesn’t hurt but we could!

**Comment by Chris2011** [comment]
Yeah, I will leave it as it is if something unexpected happen for the users they play around. It is still good documentation :)

**Pull request merged**
